services:
  postgres-db:
    container_name: tracker
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: tracker_dev
      POSTGRES_PASSWORD: secure-p@sswords-R-long
      POSTGRES_DB: tracker
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5411:5432"
volumes:
  postgresql_data:
    driver: local