CREATE TABLE game
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    type            VARCHAR(255),
    rating          FLOAT,
    player_range_id BIGINT,
    is_live         BOOLEAN,
    CONSTRAINT pk_game PRIMARY KEY (id)
);

CREATE TABLE player_range
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    min_players    INTEGER,
    max_players    INTEGER,
    is_multiplayer BOOLEAN,
    CONSTRAINT pk_playerrange PRIMARY KEY (id)
);

ALTER TABLE game
    ADD CONSTRAINT uc_game_player_range UNIQUE (player_range_id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_PLAYER_RANGE FOREIGN KEY (player_range_id) REFERENCES player_range (id);